# Generated by Django 4.0.5 on 2022-07-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_sold',
            field=models.IntegerField(default=0),
        ),
    ]
