# Generated by Django 4.0.5 on 2022-07-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderproduct_variations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('success', 'success'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
